# Exercise 6-1
# If set A = {L M N O P} and set B = {P Q R S T}, what sets are generated by the 
# following operations?
 • A union B     --> {L M N O P Q R S T}
 • A union all B --> {L M N O P P Q R S T}
 • A intersect B --> {P}
 • A except B    --> {L M N O}
 
# Exercise 6-2
# Write a compound query that finds the first and last names of all actors and 
# customers whose last name starts with L.
SELECT a.first_name, a.last_name
  FROM actor AS a
 WHERE a.last_name LIKE 'L%'
 UNION
SELECT c.first_name, c.last_name
  FROM customer AS c
 WHERE c.last_name LIKE 'L%';
# +------------+--------------+
# | first_name | last_name    |
# +------------+--------------+
# | MATTHEW    | LEIGH        |
# | JOHNNY     | LOLLOBRIGIDA |
# | MISTY      | LAMBERT      |
# .............................
# | LEWIS      | LYMAN        |
# | JACKIE     | LYNCH        |
# +------------+--------------+
# 24 rows in set (0.00 sec)
 
# Exercise 6-3
# Sort the results from Exercise 6-2 by the last_name column.
SELECT a.first_name, a.last_name
  FROM actor AS a
 WHERE a.last_name LIKE 'L%'
 UNION
SELECT c.first_name, c.last_name
  FROM customer AS c
 WHERE c.last_name LIKE 'L%'
 ORDER BY last_name;
# +------------+--------------+
# | first_name | last_name    |
# +------------+--------------+
# | MISTY      | LAMBERT      |
# | JACOB      | LANCE        |
# | RENEE      | LANE         |
# ............................. 
# | LEWIS      | LYMAN        |
# | JACKIE     | LYNCH        |
# +------------+--------------+
# 24 rows in set (0.00 sec)
